version: '2.0'


services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /data/elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      - backend

  logstash:
    container_name: logstash
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - /data:/data:ro
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    depends_on:
      - elasticsearch
    networks:
      - 1frontend
      - 2frontend
      - 3frontend
      - backend

  kibana:
    container_name: kibana
    build:
      context: kibana/
    #ports:
    #  - "5601:5601"
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch
    networks:
      - backend
      #- 4frontend

  1pymodbus:
    container_name: 1modbus
    build:
      context: ./modbus
    ports:
      - "502:502"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "/root/server.py", "0"]
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    networks:
      - 1frontend

  apache:
    container_name: apache
    build:
      context: ./apache
    ports:
      -  "80:80"
    environment:
      APACHE_RUN_USER: "www-data"
      APACHE_RUN_GROUP: "www-data"
      APACHE_LOG_DIR: "/var/log/apache2"
      APACHE_RUN_DIR: "/var/run/apache2"
    volumes:
      - /data/apache:/var/log/apache2:rw
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    networks:
      - 2frontend

  ssh_kipo:
    container_name: ssh_kipo
    build:
      context: ./ssh
    ports:
      - "22:2222"
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    volumes:
      - /data/ssh_kippo:/kippo-app/log/
    networks:
      - 3frontend

networks:
  1frontend:
  2frontend:
  3frontend:
  #4frontend:
  backend:
