version: '2.0'


services:

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /data/elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      - 1frontend
      - 2frontend
      - 3frontend
      - 4frontend
      - backend
    restart: on-failure

  logstash:
    container_name: logstash
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - /data:/data
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    depends_on:
      - elasticsearch
    networks:
      - 1frontend
      - 2frontend
      - 3frontend
      - 4frontend
      - backend
    restart: on-failure

  kibana:
    container_name: kibana
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch
    networks:
      - 1frontend
      - 2frontend
      - 3frontend
      - 4frontend
      - backend
    restart: on-failure

  1pymodbus:
    container_name: 1modbus
    build: 
      context: ./modbus
    ports:
      - "502:502"
    volumes:
      - /data/modbus/1log:/var/log/modbus
    environment:
             - PYTHONUNBUFFERED=1
    command: ["python3", "/root/server.py", "0"]
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    networks:
      - 1frontend
    restart: on-failure

  2pymodbus:
    container_name: 2modbus
    build: 
      context: ./modbus
    ports:
      - "503:502"
    volumes:
      - /data/modbus/2log:/var/log/modbus
    environment:
             - PYTHONUNBUFFERED=1
    command: ["python3", "/root/server.py", "1"]
    networks:
      - 2frontend
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    restart: on-failure

  3pymodbus:
    container_name: 3modbus
    build: 
      context: ./modbus
    ports:
      - "504:502"
    volumes:
      - /data/modbus/3log:/var/log/modbus
    environment:
             - PYTHONUNBUFFERED=1
    command: ["python3", "/root/server.py", "2"]
    networks:
      - 3frontend
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    restart: on-failure

  4pymodbus:
    container_name: 4modbus
    build: 
      context: ./modbus
    ports:
      - "505:502"
    volumes:
      - /data/modbus/4log:/var/log/modbus
    environment:
             - PYTHONUNBUFFERED=1
    command: ["python3", "/root/server.py", "3"]
    networks:
      - 4frontend
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    restart: on-failure


networks:
  1frontend:
  2frontend:
  3frontend:
  4frontend:
  backend:

