FROM debian:latest
EXPOSE 502/tcp
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    python3 \
    python3-dev \
    python3-pip  \
    git \
    python3-setuptools \
    virtualenv && \ 
    apt-get autoremove && \
    apt-get clean && \
    pip3 install -U python-logstash 
RUN git clone https://github.com/lightoyou/HoneyPot_CDSI_pymodbus.git
RUN cd HoneyPot_CDSI_pymodbus && python3 setup.py install
COPY ./server.py /root
CMD ["python3","/root/server.py","0"]
