FROM debian:latest
EXPOSE 502/tcp
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    python3 \
    python3-dev \
    python3-pip && \
    apt-get autoremove && \
    apt-get clean && \
    pip3 install -U pymodbus
    #useradd -ms /bin/bash pymodbus
COPY server.py /root
#USER pymodbus
CMD ["/root/server.py"]
ENTRYPOINT ["python3"]
