FROM debian:latest 

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    python3 \
    python3-dev \
    python3-pip && \
    apt-get autoremove && \
    apt-get clean && \ 
    pip3 install -U pymodbus 
    #useradd -ms /bin/bash pymodbus
COPY v0.2.py /root
#USER pymodbus
CMD ["/root/v0.2.py"]
ENTRYPOINT ["python3"] 
